### PR TITLE
Require Python 3.9

### PR DESCRIPTION
**Pull request by saraedum**
build with Python 3.8 seems to fail with

```
In file included from /home/conda/feedstock_root/build_artifacts/cypari2_1705557903378/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.8/pytime.h:6,
                   from /home/conda/feedstock_root/build_artifacts/cypari2_1705557903378/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.8/Python.h:85,
                   from cypari2/convert.c:50:
  cypari2/pycore_long.h: In function '_PyLong_SetSignAndDigitCount':
  cypari2/pycore_long.h:92:13: error: 'o' undeclared (first use in this function); did you mean 'op'?
     92 |     Py_SIZE(o) = size;
        |
```

also our CI only tests with Python 3.9+ so that seem to be required by now.

In any case, active support for Python 3.8 ended May 2021 and security support is going to end in October 2024.

### CODE REVIEW

**Comment by tornaria** [comment]
This was fixed in #146.

File: README.rst [hunk 1]
```diff
@@ -25,7 +25,7 @@ Requirements:
   https://doc.sagemath.org/html/en/reference/spkg/pari#spkg-pari
   for availability in distributions (GNU/Linux, conda-forge, Homebrew, FreeBSD),
   or install from source.
-- Python >= 3.6
+- Python >= 3.9
```
Comment (saraedum) [inline README.rst:28]:
```suggestion
- Python >= 3.8
```

File: setup.py [hunk 2]
```diff
@@ -68,6 +68,7 @@ def run(self):
 setup(
     name='cypari2',
     version=VERSION,
+    python_requires=">=3.9",
```
Comment (saraedum) [inline setup.py:71]:
```suggestion
    python_requires=">=3.8",
```

**Comment by mkoeppe** [comment]
Indeed 3.8 is still broken. Let's remove it?
